### ISSUE TITLE
Send To Desktop does not work on non-English language systems

### ISSUE THREAD

**Issue by skeleton221** [Intika-Linux-Plasmoid/plasma-service-dolphin-send-to-desktop#1]
hello, as I also wrote on the openDesktop page, the add-on does not work with non-English user folders.
to fix the problem just change:
Exec=ln -s %F ~/Desktop
to
Exec=/bin/bash -c "ln -s %F $(grep DESKTOP ~/.config/user-dirs.dirs | cut -d'"' -f2)"

suggestion: you could add the "Link Here" option Like so:

[Desktop Entry]
Type=Service
ServiceTypes=KonqPopupMenu/Plugin
MimeType=all/all;
X-KDE-StartupNotify=false
Actions=sendDesktop;LinkHere
X-KDE-Submenu=Send To...
X-KDE-Submenu[it]=Invia a...
InitialPreference=99
Version=5.21

[Desktop Action sendDesktop]
Name=Send to Desktop (ln -s)
Name[it]=Invia Alla Scrivania (ln -s)
Exec=/bin/bash -c "ln -s %F $(grep DESKTOP ~/.config/user-dirs.dirs | cut -d'"' -f2)"
Icon=desktop

[Desktop Action LinkHere]
Name=Create Link Here (ln -s)
Name[it]=Crea Collegamento  Qui (ln -s)
Exec=/bin/bash -c "ln -s %F ./$(basename "%F" )-link"
Icon=desktop
NOTA: The comment I wrote on OpenDesktop is old and I made other changes to the .desktop file written above.

**Comment by intika** [comment]
Thank you for the detailed report i'll fix that on the next version, the bug will be followed here https://github.com/Intika-KDE-Plasmoids/plasma-service-dolphin-send-to-desktop/issues/2

i'll let you know here as well when it's fixed ;)
